---

- name: First touch
  hosts: digital_ocean
  user: root

  tags: initial

  tasks:
    - name: Update system
      apt:
        update_cache: yes
        upgrade: yes

    - name: Reboot
      reboot:

    - name: Add user
      shell: >
        printf '%s\n' {{ ansible_become_pass }} {{ ansible_become_pass }} | adduser --gecos "" {{ main_user_name }}
      args:
        executable: /bin/bash

    - name: Make user sudo
      command: usermod -aG sudo {{ main_user_name }}

    - name: Create ssh folder for user
      file:
        path: /home/{{ main_user_name }}/.ssh/
        state: directory
      become: true
      become_user: "{{ main_user_name }}"

    - name: Copy authorization_keys to ssh folder
      copy:
        src: "{{ ssh_key_public_file }}"
        dest: /home/{{ main_user_name }}/.ssh/authorized_keys
        mode: 0644
      become: true
      become_user: "{{ main_user_name }}"

- name: Security touch
  hosts: digital_ocean
  user: "{{ main_user_name }}"
  become: true

  tags: initial

  tasks:
    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin\syes'
        line: 'PermitRootLogin no'
      notify: Restart SSHD

    - name: Configure UFW
      community.general.ufw:
        state: enabled
        rule: allow
        port: ssh

  handlers:
    - name: Restart SSHD
      service:
        name: sshd
        state: restarted

- name: User Environment touch
  hosts: digital_ocean
  user: "{{ main_user_name }}"

  vars:
    source_nvm: . ~/.nvm/nvm.sh

  tasks:
    # NodeJs
    
    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
      args:
          executable: /bin/bash
          creates: "~/.nvm/nvm.sh"
      tags: nodejs

    - name: "Install latest stable NodeJs"
      shell: "{{ source_nvm }} && nvm install --lts"
      args:
        executable: /bin/bash
        creates: "~/.nvm/versions/node"
      tags: nodejs

    # Vim

    - name: Copy vimrc
      copy:
        src: ../.vimrc
        dest: ~/.vimrc

    # Nginx
    
    - name: Install nginx
      apt:
        name: nginx
        state: latest
      become: true
      tags: nginx

    - name: Start nginx service
      service:
        name: nginx
        state: started
      become: true
      tags: nginx

    - name: Open http port
      community.general.ufw:
        rule: allow
        port: http
      become: true
      tags: nginx

    # Git

    - name: Copy ssh key for github
      copy:
        src: "{{ ssh_private_key_for_github }}"
        dest: ~/.ssh/id_rsa
        mode: 0600
      tags: git

    # Configure node projects deployment tools

    - name: Create projects folder
      file:
        path: ~/projects/
        state: directory
      tags: node_deploy_tools

    - name: Install Yarn
      shell: "{{ source_nvm }} && npm install -g yarn"
      args:
        executable: /bin/bash
      tags: node_deploy_tools

    - name: Install PM2
      shell: "{{ source_nvm }} && npm install -g pm2"
      args:
        executable: /bin/bash
      tags: node_deploy_tools
...
